### ISSUE TITLE
Describe SD-JWT as an alternative for selective disclosure

### ISSUE THREAD

**Issue by Sebastian-Elfors-IDnow** [w3c/vc-jose-cose#118]
The descriptions about selective disclosure in the W3C Verifiable Credentials specification could be extended by mentioning [SD-JWT (Selective Disclosure JWT)](https://www.ietf.org/id/draft-fett-oauth-selective-disclosure-jwt-02.html).

The [SD-JWT specification](https://www.ietf.org/id/draft-fett-oauth-selective-disclosure-jwt-02.html) is currently an IETF Internet-Draft, which specifies the SD-JWT as a signed JWT with salted/hashed values of a list of claims. The SD-JWT draft also specifies SD-JWT Salt/Value Container (SVC) that contains mappings between raw claim values contained in the SD-JWT and the salts for each claim value. It also specifies the SD-JWT-R, which is a JWT created by the holder that contains a subset of the claim values the holder wants to release during presentment.

The approach with SD-JWT is similar to the MSO object in the ISO 18013-5 (mobile driving license). SD-JWTs can be presented both online and offline.

There is an [example of a SD-JWT as a W3C Verifiable Credential](https://www.ietf.org/id/draft-fett-oauth-selective-disclosure-jwt-02.html#name-example-4-w3c-verifiable-cr) in an appendix of the specification.

**Comment by selfissued** [comment]
PR #149 addresses this

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section6-7) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.7. Describe SD-JWT as an alternative for selective disclosure (issue vc-jose-cose#118)

_See github issue [vc-jose-cose#118](https://github.com/w3c/vc-jose-cose/issues/118)._




**Michael Jones:** this issue will be closed when the PR is merged.  

</details>

**Comment by Sakurann** [comment]
PR merged
