### ISSUE TITLE
Better references to OIDC key discovery

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#127]
@Sakurann you mentioned on the SCITT PR related to key discovery, a preference for better citations, and less "repeating" / "redefining"....

Would you be willing to open a PR to address https://openid.net/specs/openid-connect-userinfo-vc-1_0.html#name-userinfo-vc-verification

after https://github.com/w3c/vc-jose-cose/pull/122 is merged?

**Comment by Sakurann** [comment]
current well-known URIs section should not use /.well-known/openid-configuration path, because that path is used for the OIDC AS metadata which must not be conflated with the metadata of a credential issuer. Credential issuer may choose to use the same keys to sign ID Tokens and VCs, but it should also have a choice to use different keys (which is what I would expect will happen in many cases). 

My recommendation would be to use `/.well-known/jwt-issuer`.

or whatever path will be agreed upon [in sd-jwt vc spec](https://vcstuff.github.io/draft-terbu-sd-jwt-vc/draft-terbu-oauth-sd-jwt-vc.html#section-5.1). because there are [PR #118](https://github.com/vcstuff/draft-terbu-sd-jwt-vc/pull/118) and [issue #101](https://github.com/vcstuff/draft-terbu-sd-jwt-vc/issues/101) that have suggested to change the path, but so far jwt-issuer seems to be the way to go.

**Comment by selfissued** [comment]
I agree with the use of `/.well-known/jwt-issuer` for the reasons cited.

**Comment by OR13** [comment]
are we sure a `/.well-known/jwt-issuer` can issue `sd-jwt` given its not a `jwt` ? sorta trolling, sorta not.

**Comment by Sakurann** [comment]
i think we are...?

**Comment by Sakurann** [comment]
PR merged
