### ISSUE TITLE
Should we comment on "principle"?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#35]
Should we define a relationship between `principle` / `entity` and the `issuer` / `subject` / `holder` / `verifier`?

Seems like that would be helpful for people coming with the JWT ecosystem first learning about VCs and the 3 party model.

**Comment by Sakurann** [comment]
would recommend using issuer / subject / holder / verifier throughout the text, but in the definition put the relationship with OAuth/JWT terms.

For example, in OpenID4VC specs we said
> Verifier: The entity that requests, receives and validates Verifiable Presentations. During presentation of Credentials, Verifier acts as an OAuth 2.0 Client towards the Wallet that is acting as an OAuth 2.0 Authorization Server. The Verifier is a specific case of OAuth 2.0 Client, just like Relying Party (RP) in [@OpenID.Core].

**Comment by OR13** [comment]
@Sakurann I like that text... Can we add normative or informative references to it?

**Comment by selfissued** [comment]
Does this suggestion still seem pertinent or have events passed it by?  (At present, is the oldest remaining vc-jose-cose issue.)

**Comment by OR13** [comment]
Still seems relevant, but I would also be ok closing it.

**Comment by selfissued** [comment]
Neither of the words "principle" or "principal" occur in the vc-jose-cose spec.  (The only use of either in vc-data model is at https://w3c.github.io/vc-data-model/#the-principle-of-data-minimization .)  I suspect that means we can close this issue.

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section6-12) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.12. Should we comment on "principle"? (issue vc-jose-cose#35)

_See github issue [vc-jose-cose#35](https://github.com/w3c/vc-jose-cose/issues/35)._




**Michael Jones:** this is terminology. we already done a good job in the specs on terminology.  

> *Manu Sporny:* +1 to close this issue :).

**Brent Zundel:** this one is post-cr.  
� any objections to close?  
� no objections, closing after script has been generated.  

</details>
