### ISSUE TITLE
Describe how `cnf` is allowed to be used for "binding"

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#52]
How should a verifier interpret the `cnf` claim when it is present in a `vc-jwt-2.0`.

**Comment by selfissued** [comment]
https://w3c.github.io/vc-jose-cose/#cnf currently says:
> If cnf is present in the [Protected Header](https://www.rfc-editor.org/rfc/rfc7515#section-4.1) or the [JWT Claims ](https://www.rfc-editor.org/rfc/rfc7519#section-4.1.1), a [verifier](https://www.w3.org/TR/vc-data-model/#dfn-verifier) can use this parameter to obtain a [JSON Web Key](https://www.rfc-editor.org/rfc/rfc7517#section-4) to use in the [verification](https://www.w3.org/TR/vc-data-model/#dfn-verify) process.

> If kid is also present in the [Protected Header](https://www.rfc-editor.org/rfc/rfc7515#section-4.1), it is expected to be useful to distinguish the specific key used.

I question the second sentence.  Wouldn't the `kid` be used to determine the issuer's key - not the confirmation key?

**Comment by iherman** [comment]
The issue was discussed in a [meeting](https://www.w3.org/2017/vc/WG/Meetings/Minutes/2023-09-14-vcwg#section6-11) on 2023-09-14

- no resolutions were taken

<details><summary><i>View the transcript</i></summary>

#### 6.11. Describe how `cnf` is allowed to be used for "binding" (issue vc-jose-cose#52)

_See github issue [vc-jose-cose#52](https://github.com/w3c/vc-jose-cose/issues/52)._




**Michael Jones:** this issue has PR too? closing once merging that one.  

**Manu Sporny:** rfc7800 defines how to use cnf claim for proof of possession.  
� is that what you are saying/.  

**Michael Jones:** yes.  

</details>
