### ISSUE TITLE
Change `typ` values for JSON-LD claim sets?

### ISSUE THREAD

**Issue by OR13** [w3c/vc-jose-cose#57]
currently we have:

`vc+ld+jwt`
`vc+ld+cwt`

I think this may not be correct, since `+ld` is not a valid suffix?

However I like this approach because of how intuitive it is compared to 

`credential+ld+json`

potential alternative would be:

`vc-ld+jwt`
`vc-ld+cwt`

**Comment by TallTed** [comment]
I *strongly* advise discussing media types with their full names, rather than dropping the `application/` that JWTs advise to omit *when building the JWT* (I could not find similar advice about CWTs), but which is then treated as being invisibly present.

> I think this may not be correct, since `+ld` is not a valid suffix?

The `application/` suffixes which must be valid do not include `+ld`; rather, they are 
`+ld+jwt` (and `+jwt`) and 
`+ld+cwt` (and `+cwt`), 
which means that 
`application/ld+jwt`, 
`application/jwt`, 
`application/ld+cwt`, and 
`application/cwt` 
must be defined and registered, before or simultaneously with definition and registration of
`application/vc+ld+jwt` and 
`application/vc+ld+cwt`.

_If_ I correctly understand the interrelationships of these types, a better set might be 
`application/vc+ld+json+jwt`, 
`application/ld+json+jwt`, 
`application/json+jwt`, 
`application/jwt`, 
`application/ld+cbor+cwt`, 
`application/vc+ld+cbor+cwt`, 
`application/cbor+cwt`, and 
`application/cwt`,
because these are *somewhat* likely to increase comprehension of derivation, 
though I realize `cbor` and `json` are implicit in `cwt` and `jwt`, respectively,
and neither `application/json+jwt` nor `application/cbor+cwt` are really subtypes of `application/jwt` or `application/cwt` ....

All that said — I am not convinced of 
* the intuitiveness of any of these to people outside our groups
* that we have decided how to handle {presentation|verifiable presentation} media types alongside {credential|verifiable credential} media types
* whether we have decided to have a single media type that encompasses both verifiable (with proofs) and non-verifiable (without proofs) {credentials|presentations}, and if so, whether that/those type/s reflects the possibility of verifiability

**Comment by thomas-fossati** [comment]
> potential alternative would be:
>
> vc-ld+jwt
> vc-ld+cwt

The `+cwt` structured suffix is not present in the [SSS registry](https://www.iana.org/assignments/media-type-structured-suffix/media-type-structured-suffix.xhtml).  In an [IETF-RATS draft](https://datatracker.ietf.org/doc/html/draft-ietf-rats-eat-media-type-02#section-6.1) we are requesting its registration though, so you may want to keep an eye on that document -- and possibly help pushing it through the RFC Editor line ;-)

**Comment by OR13** [comment]
I don't think we can call JSON-LD secured with a CoseSign1 a CWT, based on this:

https://mailarchive.ietf.org/arch/msg/cose/sTWvCwbX6RjMi1pV3kTn6huX1fk/

**Comment by OR13** [comment]
This PR can be closed when https://github.com/w3c/vc-jwt/pull/120 is merged

**Comment by Sakurann** [comment]
PR was merged
