### ISSUE TITLE
Determine if Privacy Section can be normative

### ISSUE THREAD

**Issue by mprorock** [w3c/vc-jose-cose#82]
Determine if the privacy section can be normative, and adjust language as appropriate in the privacy section.

**Comment by brentzundel** [comment]
It is not traditional for a privacy considerations section to be normative.
That doesn't mean that cannot be done here, but it may be better to introduce the normative requirements in a different part of the spec and then discuss them in more detail in the privacy considerations section, rather than making the section itself normative.

**Comment by OR13** [comment]
Marked pending close over 1 week ago, closing.
